# Setup
title:        Commonplace Devlog
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       wonbae Kim
  url:        http://wonbae.github.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
